# Generated by Django 4.2.1 on 2023-05-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_description_alter_course_endmsg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subtitle',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
