# Generated by Django 4.2.1 on 2023-05-28 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_subtitle_alter_course_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='course',
        ),
        migrations.DeleteModel(
            name='Lecture',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
