# Generated by Django 4.2.1 on 2023-05-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_session_course_delete_lecture_delete_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='subcat',
            name='description',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='subcat',
            name='name',
            field=models.CharField(max_length=700),
        ),
    ]
