# Generated by Django 4.2.1 on 2023-06-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_subcat_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
