# Generated by Django 4.2.1 on 2023-06-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_course_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='reason',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
