# Generated by Django 4.2.1 on 2023-06-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_course_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='reason',
            field=models.CharField(default='', max_length=600, null=True),
        ),
    ]
