# Generated by Django 4.2.1 on 2023-06-16 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_enrolledcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolledcourse',
            name='progress',
        ),
    ]
