# Generated by Django 4.2.1 on 2023-06-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_remove_enrolledcourse_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledcourse',
            name='courseprogress',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
