# Generated by Django 4.2.1 on 2023-06-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_enrolledcourse_courseprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_requested',
            field=models.BooleanField(default=False),
        ),
    ]
