# Generated by Django 4.2.1 on 2023-06-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_order_addrress1_order_addrress2_order_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
