# Generated by Django 4.2.1 on 2023-06-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_alter_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sub_total',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
