# Generated by Django 4.2.1 on 2023-07-02 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
    ]
