# Generated by Django 4.2.1 on 2023-05-28 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csession', '0004_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csession.sessions'),
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
