# Generated by Django 4.2.1 on 2023-06-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csession', '0005_alter_lecture_session_delete_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='content',
            new_name='type',
        ),
        migrations.AddField(
            model_name='lecture',
            name='material',
            field=models.FileField(null=True, upload_to='photos/course'),
        ),
    ]
