# Generated by Django 4.2.1 on 2023-06-16 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0015_remove_enrolledcourse_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('csession', '0006_rename_content_lecture_type_lecture_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('current_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.enrolledcourse')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csession.lecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
