# Generated by Django 4.2.1 on 2023-06-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('min_amount', models.IntegerField(null=True)),
                ('activ_date', models.DateField(null=True)),
                ('exp_date', models.DateField(null=True)),
                ('allowed_users', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
            ],
        ),
    ]
